@extends("layouts.home")
@section("content")
    @include("frontend.home.sections.about")
    @include("frontend.home.sections.special")
    @include("frontend.home.sections.menu")
    @include("frontend.home.sections.book")
    @include("frontend.home.sections.contact")
    @include("frontend.home.sections.footer")
@endsection
